#-------------------------------------------------------------------------------
# Name:        constants.py
# Purpose:     Project's constants values
# Author:      Zahra Pourizadeh
# Created:     01/01/2025
#-------------------------------------------------------------------------------

samplerate = 44100
duration = 0.1  # Duration of each audio block (in seconds)

# The lowest & highest frequency generated by the synthesizer
frequency_low = 100 
frequency_high = 10000

# The lowest & highest amplitude generated by the synthesizer
amplitude_low = 0
amplitude_high = 1

# The low & high values of Delay effect
delay_time_low = 0.01
delay_time_high = 0.5
delay_feedback_low = 0
delay_feedback_high = 0.9

# The low & high values of Tremolo effect
tremolo_depth_low = 0
tremolo_depth_high = 0.5
tremolo_rate_low = 1
tremolo_rate_high = 20

# The low & high values of Vibrato effect
vibrato_depth_low = 0
vibrato_depth_high = 0.5
vibrato_rate_low = 1
vibrato_rate_high = 20